[package]
name = "rmk-types"
version = "0.2.1"
edition = "2024"
authors = ["Haobo Gu <haobogu@outlook.com>"]
description = "Common types in RMK"
homepage = "https://github.com/haobogu/rmk"
repository = "https://github.com/haobogu/rmk"
license = "MIT OR Apache-2.0"
resolver = "2"

[dependencies]
defmt = { version = "1.0", optional = true }
log = { version = "0.4", optional = true }

serde = { version = "1", default-features = false, features = ["derive"] }
postcard = { version = "1", features = ["experimental-derive"] }
strum = { version = "0.27", default-features = false, features = ["derive"] }

bitfield-struct = "0.12"

[features]
defmt = [
    "dep:defmt",
    "postcard/defmt",
]
