[package]
name = "rmk-sf32lb52x-usb"
version = "0.2.0"
authors = ["Haobo Gu <haobogu@outlook.com>", "Decaday<myDecaday@outlook.com>"]
description = "Keyboard firmware written in Rust"
homepage = "https://github.com/haobogu/rmk"
repository = "https://github.com/haobogu/rmk"
readme = "../../README.md"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
rmk = { path = "../../../rmk", default-features = false, features = ["col2row", "defmt"] }

sifli-hal = { version = "0.1.1", features = [
    "defmt",
    "sf32lb52x", 
    "time-driver-gptim2"
] }
embassy-time = { version = "0.5", features = ["defmt", "defmt-timestamp-uptime", "tick-hz-32_768"] }
embassy-executor = { version = "0.9", features = [
    "defmt",
    "arch-cortex-m",
    "executor-thread",
] }
cortex-m-rt = { version = "0.7.3", features = ["set-sp", "set-vtor"] }
portable-atomic = { version = "1.11" }
defmt = "1.0"
defmt-rtt = "1.0"
panic-probe = { version = "1.0", features = ["print-defmt"] }
cortex-m = { version = "0.7.7", features = ["critical-section-single-core"] }

[build-dependencies]
xz2 = "0.1.7"
json = "0.12"
const-gen = "1.6"

[[bin]]
name = "rmk-sf32lb52x-usb"
test = false
bench = false

[profile.dev]
codegen-units = 1      # better optimizations
debug = true
opt-level = "s"
overflow-checks = true
lto = "fat"
panic = 'unwind'

[profile.release]
codegen-units = 1       # better optimizations
debug = true            # no overhead for bare-metal
opt-level = "z"         # optimize for binary size
overflow-checks = false
lto = "fat"
