[package]
name = "rmk-hpm5300"
version = "0.2.0"
authors = ["Haobo Gu <haobogu@outlook.com>"]
description = "Keyboard firmware written in Rust"
homepage = "https://github.com/haobogu/rmk"
repository = "https://github.com/haobogu/rmk"
readme = "../../README.md"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
rmk = { path = "../../../rmk" }
embedded-storage-async = "0.4"
hpm-hal = { git = "https://github.com/hpmicro/hpm-hal", rev = "756236cd28de5320999444fbb77908e6030042a1", features = [
    "rt",
    "embassy",
    "hpm5361",
    "defmt",
    "usb-pin-reuse-hpm5300",
] }
embassy-time = { version = "0.4", features = ["tick-hz-1_000_000", "defmt"] }
riscv-rt = "0.12.2"
riscv = { version = "0.11.1", features = ["critical-section-single-hart"] }
embassy-executor = { version = "0.7", features = [
    "defmt",
    "nightly",
    "executor-thread",
    "arch-riscv32",
] }
defmt = "1.0"
defmt-rtt = "1.0"

[patch.crates-io]
embassy-sync = { git = "https://github.com/embassy-rs/embassy.git", rev = "f35aa4005a63e8d478b2b95aaa2bfb316b72dece" }
embassy-futures = { git = "https://github.com/embassy-rs/embassy.git", rev = "f35aa4005a63e8d478b2b95aaa2bfb316b72dece" }
embassy-executor = { git = "https://github.com/embassy-rs/embassy.git", rev = "f35aa4005a63e8d478b2b95aaa2bfb316b72dece" }

[build-dependencies]
xz2 = "0.1.7"
json = "0.12"
const-gen = "1.6"

[[bin]]
name = "rmk-hpm5300"
test = false
bench = false

[profile.dev]
codegen-units = 1      # better optimizations
debug = true
opt-level = 1
overflow-checks = true
lto = false
panic = 'unwind'

[profile.release]
codegen-units = 1       # better optimizations
debug = true            # no overhead for bare-metal
opt-level = "z"         # optimize for binary size
overflow-checks = false
lto = "fat"
