[package]
name = "rmk-hpm5300"
version = "0.2.0"
authors = ["Haobo Gu <haobogu@outlook.com>"]
description = "Keyboard firmware written in Rust"
homepage = "https://github.com/haobogu/rmk"
repository = "https://github.com/haobogu/rmk"
readme = "../../README.md"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
rmk = { path = "../../../rmk" }
embedded-storage-async = "0.4"
hpm-hal = { git = "https://github.com/hpmicro-rs/hpm-hal", rev = "a52f5ec", features = [
    "rt",
    "embassy",
    "hpm5361",
    "usb-pin-reuse-hpm5300",
] }
embassy-time = { version = "0.3", git = "https://github.com/embassy-rs/embassy", rev = "1ff1f00", features = ["tick-hz-1_000_000", "defmt"] }
riscv-rt = "0.12.2"
riscv = { version = "0.11.1", features = ["critical-section-single-hart"] }
embassy-executor = { version = "0.6", git = "https://github.com/embassy-rs/embassy", rev = "1ff1f00", features = [
    "defmt",
    "nightly",
    "task-arena-size-8192",
    "executor-thread",
    "integrated-timers",
    "arch-riscv32",
] }
defmt = "0.3"
defmt-rtt = "0.4"
# panic-probe = { version = "0.3", features = ["print-defmt"] }


[patch.crates-io]
embassy-sync = { version = "0.6", git = "https://github.com/embassy-rs/embassy", rev = "01d8508" }
embassy-futures = { version = "0.1", git = "https://github.com/embassy-rs/embassy", rev = "01d8508" }
embassy-executor = { version = "0.6", git = "https://github.com/embassy-rs/embassy", rev = "01d8508" }
embassy-embedded-hal = { version = "0.2", git = "https://github.com/embassy-rs/embassy", rev = "01d8508" }
embassy-time = { version = "0.3", git = "https://github.com/embassy-rs/embassy", rev = "01d8508" }
embassy-time-driver = { version = "0.1", git = "https://github.com/embassy-rs/embassy", rev = "01d8508" }

[build-dependencies]
xz2 = "0.1.7"
json = "0.12"
const-gen = "1.6"

[[bin]]
name = "rmk-hpm5300"
test = false
bench = false

[profile.dev]
codegen-units = 1      # better optimizations
debug = true
opt-level = 1
overflow-checks = true
lto = false
panic = 'unwind'

[profile.release]
codegen-units = 1       # better optimizations
debug = true            # no overhead for bare-metal
opt-level = "z"         # optimize for binary size
overflow-checks = false
lto = "fat"
