[package]
name = "rmk-config"
version = "0.1.6"
edition = "2021"
authors = ["Haobo Gu <haobogu@outlook.com>"]
description = "Config crate of RMK"
homepage = "https://github.com/haobogu/rmk"
repository = "https://github.com/haobogu/rmk"
license = "MIT OR Apache-2.0"
resolver = "2"

[dependencies]
embedded-hal = { version = "1.0.0" }
serde = { version = "1.0", optional = true }
serde_derive = { version = "1.0", optional = true }
embassy-nrf = { version = "0.2", git = "https://github.com/embassy-rs/embassy", rev = "1ff1f00", features = [
    "unstable-pac",
    "time",
], optional = true }

[features]
default = []
toml = ["serde", "serde_derive"]
_esp_ble = []
_nrf_ble = ["embassy-nrf"]
