[keyboard]
usb_enable = true

[ble]
enabled = true

[storage]
enabled = true
# Storage starts from 640K
start_addr = 0xA0000
# Storage uses 128K = 640K ~ 768K
num_sectors = 32

[chip]
# DCDC regulator 0 enabled (default: true)
dcdc_reg0 = false
# DCDC regulator 1 enabled (default: true)
dcdc_reg1 = false
# DCDC regulator 0 voltage: "3V3" or "1V8" (default: "3V3")
dcdc_reg0_voltage = "3V3"
