[tasks.install-llvm-tools]
install_crate = { rustup_component_name = "llvm-tools" }

[tasks.flip-link]
install_crate = { crate_name = "flip-link", binary = "flip-link", test_arg = ["-h"] }

[tasks.objcopy]
install_crate = { crate_name = "cargo-binutils", binary = "cargo", test_arg = [
    "objcopy",
    "--help",
] }
command = "cargo"
args = ["objcopy", "--release", "--", "-O", "ihex", "rmk.hex"]
dependencies = ["install-llvm-tools", "flip-link"]

[tasks.uf2]
install_crate = { crate_name = "cargo-hex-to-uf2", binary = "cargo", test_arg = [
    "hex-to-uf2",
    "--help",
] }
command = "cargo"
args = [
    "hex-to-uf2",
    "--input-path",
    "rmk.hex",
    "--output-path",
    "rmk.uf2",
    "--family",
    "stm32f4",
]
dependencies = ["objcopy"]
