[package]
name = "ch32v307-examples"
version = "0.1.0"
edition = "2021"

[dependencies]
rmk = { path = "../../../rmk", features = ["_no_external_storage"] }
ch32-hal = { git = "https://github.com/ch32-rs/ch32-hal", rev = "749577a", features = [
    "ch32v307vct6",
    "memory-x",
    "embassy",
    "rt",
    "highcode",
    "time-driver-tim1",
] }
embassy-executor = { version = "0.6.0", features = [
    "integrated-timers",
    "arch-spin",
    "task-arena-size-32768",
    "executor-thread",
] }
static_cell = "2"
critical-section = "1.2.0"

embassy-time = "0.3.2"
embassy-usb = "0.3.0"
nb = "1.1.0"

qingke = "0.4.0"
qingke-rt = "0.4.0"

# Not working for now
defmt = "0.3"

panic-halt = "1.0.0"

[build-dependencies]
xz2 = "0.1.7"
json = "0.12"
const-gen = "1.6"

[profile.release]
strip = false   # symbols are not flashed to the microcontroller, so don't strip them.
lto = true
opt-level = "z" # Optimize for size.
