name: Unit Test

on:
  push:
    branches: ["main"]
    paths: ["rmk/**", "rmk-macro/**"]
  pull_request:
    branches: ["main"]
    paths: ["rmk/**", "rmk-macro/**"]
  workflow_dispatch:

# Cancel any currently running workflows from the same PR, branch, or
# tag when a new workflow is triggered.
#
# https://stackoverflow.com/a/66336834
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

env:
  CARGO_TERM_COLOR: always

jobs:
  unit_test:
    name: Run RMK unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
        featuresets:
          - "log,std"
          - "storage"
          - "vial"
          - "split"
          - "split,vial"
          - "split,storage"
          - "vial,storage"
          - "split,vial,storage"
    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Run tests
        working-directory: ./rmk
        run: cargo test --no-default-features --features=${{ matrix.featuresets }} --verbose
  rmk_macro_test:
    name: Run tests for rmk-macro
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run rmk-macro tests
        working-directory: ./rmk-macro
        run: cargo test 
  